### PR TITLE
Bump guzzlehttp/guzzle

### PR DESCRIPTION
**Pull request by nextdayflight**
In composer.json:
- Fix homepage
- Allow [guzzlehttp/guzzle ](https://packagist.org/packages/guzzlehttp/guzzle) 7.4

### CODE REVIEW

**Comment by nextdayflight** [comment]
@tristankenney ping!

**Comment by nextdayflight** [comment]
@tristankenney ping! again!

**Comment by tristankenney** [comment]
> @tristankenney ping! again!

Soz! I'd actually looked at this. 

My only thought was to regenerate the client using the latest version of the generator — it uses ^7.0 guzzle, and it looks like it's got some slight improvements to error handling. 

Having said that, this is all good too. Dealer's choice.

**Review by tristankenney — APPROVED** [review]

**Comment by nextdayflight** [comment]
> > @tristankenney ping! again!
> 
> Soz! I'd actually looked at this.
> 
> My only thought was to regenerate the client using the latest version of the generator — it uses ^7.0 guzzle, and it looks like it's got some slight improvements to error handling.
> 
> Having said that, this is all good too. Dealer's choice.

Probably worth doing at some point - but it doesn't touch composer.json though right?

**Pull request merged**
